// =============================================================================
// AUTO-GENERATED — DO NOT EDIT BY HAND
// Source: my_hardware_spec.md (Blueprint, block_name="simple_timer")
// Generated by: render_blueprint.py — interface template
//
// Regeneration will overwrite this file. Human-authored extensions belong
// in a separate file (T4 protection boundary). See ../uvm_platform/README.md.
// =============================================================================

interface apb_if;
  input logic  psel;
  input logic  penable;
  input logic  pwrite;
  input logic [7:0] paddr;
  input logic [31:0] pwdata;
  output logic [31:0] prdata;
  output logic  pready;
endinterface : apb_if
