// =============================================================================
// AUTO-GENERATED — DO NOT EDIT BY HAND
// Source: my_hardware_spec.md (Blueprint, block_name="simple_timer")
// Generated by: render_blueprint.py — test template
//
// Base test class: simple_timer_base_test
//   - Instantiates the env as `m_env`
//   - Prints the topology for visibility during bring-up
//
// T4: human-authored derived tests live in separate files.
// =============================================================================

package simple_timer_test_pkg;
  import uvm_pkg::*;
  import simple_timer_pkg::*;
  import simple_timer_env_pkg::*;
  `include "uvm_macros.svh"

  class simple_timer_base_test extends uvm_test;
    `uvm_component_utils(simple_timer_base_test)

    simple_timer_env m_env;

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      m_env = simple_timer_env::type_id::create("m_env", this);
    endfunction

    function void end_of_elaboration_phase(uvm_phase phase);
      super.end_of_elaboration_phase(phase);
      uvm_top.print_topology();
    endfunction

  endclass : simple_timer_base_test

endpackage : simple_timer_test_pkg
