// =============================================================================
// AUTO-GENERATED — DO NOT EDIT BY HAND
// Source: my_hardware_spec.md (Blueprint, block_name="simple_timer")
// Generated by: render_blueprint.py — package template
//
// Contains all custom classes for simple_timer:
//   - simple_timer_vsequencer   (T3 stub: stubbed arbitrate() body)
//   - simple_timer_reg_block    (T2 placeholder: real model from SystemRDL)
//   - simple_timer_reg_adapter  (T2 placeholder: real adapter from SystemRDL)
//   - simple_timer_scoreboard   (placeholder: behavior deferred to Stage 2')
//
// External classes (NOT generated here, assumed in vendor libs):
//   - amba_apb_agent
//   - irq_monitor_agent
//   - uvm_reg_predictor
//
// Regeneration will overwrite this file. Human-authored extensions belong
// in a separate file (T4 protection boundary).
// =============================================================================

package simple_timer_pkg;
  import uvm_pkg::*;
  `include "uvm_macros.svh"

  // -------------------------------------------------------------------------
  // simple_timer_vsequencer — T3 stub
  // -------------------------------------------------------------------------
  // Virtual sequencer with stubbed arbitrate() method. When a second agent
  // is introduced (multi-agent design), this is where coordination logic
  // is supplied via a derived class registered through set_type_override_by_type.
  // Stubbing now makes the second agent a plug-in, not a rewrite (reqspec §2a).
  class simple_timer_vsequencer extends uvm_sequencer;
    `uvm_component_utils(simple_timer_vsequencer)

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    // T3 stub: empty default. Override in derived class for real coordination.
    virtual function void arbitrate();
    endfunction
  endclass

  // -------------------------------------------------------------------------
  // simple_timer_reg_block — T2 placeholder
  // -------------------------------------------------------------------------
  // Real register model is generated from SystemRDL via PeakRDL (T2). This
  // placeholder exists so the structural skeleton compiles and the env has
  // a slot for the real model to fill when T2 lands.
  class simple_timer_reg_block extends uvm_reg_block;
    `uvm_component_utils(simple_timer_reg_block)

    function new(string name = "simple_timer_reg_block");
      super.new(name, null);
    endfunction
  endclass

  // -------------------------------------------------------------------------
  // simple_timer_reg_adapter — T2 placeholder
  // -------------------------------------------------------------------------
  class simple_timer_reg_adapter extends uvm_reg_adapter;
    `uvm_component_utils(simple_timer_reg_adapter)

    function new(string name = "simple_timer_reg_adapter");
      super.new(name);
    endfunction
  endclass

  // -------------------------------------------------------------------------
  // simple_timer_scoreboard — placeholder
  // -------------------------------------------------------------------------
  // Stage 2' (per reqspec) handles protocol-level checking behavior. The
  // structural placeholder exists now so TLM analysis ports have something
  // to connect to.
  class simple_timer_scoreboard extends uvm_scoreboard;
    `uvm_component_utils(simple_timer_scoreboard)

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction
  endclass

endpackage : simple_timer_pkg
