// =============================================================================
// AUTO-GENERATED — DO NOT EDIT BY HAND
// Source: my_hardware_spec.md (Blueprint, block_name="simple_timer")
// Generated by: render_blueprint.py — env template
//
// Environment class: simple_timer_env
//   - Instantiates all components declared in the Blueprint
//   - Calls uvm_config_db::set() for every config_db entry (scope derived by
//     path_assembler, never spec-owned — T1 addendum)
//
// T4: regeneration only touches this file. Human-authored extensions
// (derived env, override components) live in separate files.
// =============================================================================

package simple_timer_env_pkg;
  import uvm_pkg::*;
  import simple_timer_pkg::*;
  `include "uvm_macros.svh"

  class simple_timer_env extends uvm_env;
    `uvm_component_utils(simple_timer_env)

    // ---------------------------------------------------------------------
    // Component handles — generated from Blueprint instances
    // ---------------------------------------------------------------------
    amba_apb_agent m_apb_agent;
    irq_monitor_agent m_irq_agent;
    simple_timer_reg_block m_regmodel;
    simple_timer_reg_adapter m_reg_adapter;
    uvm_reg_predictor m_reg_predictor;
    simple_timer_scoreboard m_scoreboard;
    simple_timer_vsequencer m_vsequencer;

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      m_apb_agent = amba_apb_agent::type_id::create("m_apb_agent", this);
      m_irq_agent = irq_monitor_agent::type_id::create("m_irq_agent", this);
      m_regmodel = simple_timer_reg_block::type_id::create("m_regmodel", this);
      m_reg_adapter = simple_timer_reg_adapter::type_id::create("m_reg_adapter", this);
      m_reg_predictor = uvm_reg_predictor::type_id::create("m_reg_predictor", this);
      m_scoreboard = simple_timer_scoreboard::type_id::create("m_scoreboard", this);
      m_vsequencer = simple_timer_vsequencer::type_id::create("m_vsequencer", this);
    endfunction

    function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);
      // TLM analysis-port connections and reg_predictor.bind() go here.
      // Stage 2' (per reqspec) handles protocol-level connections.
    endfunction

  endclass : simple_timer_env

endpackage : simple_timer_env_pkg
