// =============================================================================
// AUTO-GENERATED — DO NOT EDIT BY HAND
// Source: my_hardware_spec.md (Blueprint, block_name="simple_timer")
// Generated by: render_blueprint.py — tb_top template
//
// Testbench top: instantiates virtual interfaces and runs the test.
//   - One virtual interface per Blueprint shared asset
//   - All set() calls use scopes derived by path_assembler (T1 addendum)
//   - uvm_config_db::set() happens here, NOT in the env (so the env is
//     reusable across TB tops without modification)
//
// Clock and reset generation uses placeholders — the renderer doesn't know
// the period/phase, so it emits TODO comments at those points.
// =============================================================================

module tb_top;
  import uvm_pkg::*;
  import simple_timer_pkg::*;
  import simple_timer_env_pkg::*;
  import simple_timer_test_pkg::*;
  `include "uvm_macros.svh"

  // ---------------------------------------------------------------------------
  // DUT — placeholder. Real DUT module name comes from the spec; for Phase 1
  // the renderer emits a comment. Hook in real DUT instantiation here.
  // ---------------------------------------------------------------------------
  // simple_timer simple_timer_dut (.*);  // TODO: hook up DUT ports to interface signals

  // ---------------------------------------------------------------------------
  // Virtual interfaces — one per Blueprint shared asset
  // ---------------------------------------------------------------------------
  clk_rst_if clk_rst_vif();
  apb_if apb_ctrl_vif();
  irq_if irq_out_vif();
  // ---------------------------------------------------------------------------
  // Clock and reset — placeholders. Real values come from spec.
  // ---------------------------------------------------------------------------
  // TODO: assign clk_rst_vif.clk from a real clock generator
  // TODO: assign clk_rst_vif.rst_n from a real reset generator

  // ---------------------------------------------------------------------------
  // uvm_config_db::set() calls — scopes derived from instance tree (T1).
  // Every target_instance in the Blueprint's config_db block becomes one
  // set() here. The path string is computed by path_assembler, never typed
  // by hand.
  // ---------------------------------------------------------------------------
  initial begin
    uvm_config_db#(virtual clk_rst_if)::set(
      null, "uvm_test_top.m_env.*", "vif", clk_rst_vif);
    uvm_config_db#(virtual apb_if)::set(
      null, "uvm_test_top.m_env.m_apb_agent.*", "vif", apb_ctrl_vif);
    uvm_config_db#(virtual irq_if)::set(
      null, "uvm_test_top.m_env.m_irq_agent.*", "vif", irq_out_vif);
  end

  // ---------------------------------------------------------------------------
  // Run test
  // ---------------------------------------------------------------------------
  initial begin
    run_test("simple_timer_base_test");
  end

endmodule
